### ISSUE TITLE
Issue with ZonePowerVolumeControl.tsx

### ISSUE THREAD

**Issue by zolapop** [cbschuld/monoprice-multizone-interface#2]
Thanks for updating this script recently. I really appreciate your work on this. I've complied on two machines today and gotten this error. Can you replicate?
![error](https://user-images.githubusercontent.com/63994052/79923394-a9a97200-83f2-11ea-8118-a260ea640977.png)

/projects/monoprice-multizone-interface/src/ZonePowerVolumeControl.tsx
TypeScript error in /projects/monoprice-multizone-interface/src/ZonePowerVolumeControl.tsx(60,48):
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.  TS2345

    58 |                         style={{width:'48px'}}
    59 |                         onChange={(selected:LabeledValue)=>{
  > 60 |                             setSource(parseInt(selected.key));
       |                                                ^
    61 |                             onSourceChange(info.zone,selected.key);
    62 |                         }}
    63 |                         value={{key:source.toString(),label:getSourceIcon()}}

**Comment by cbschuld** [comment]
@zolapop - so sorry; I attempted to fix this but I am not near my amp for the next few months and can't test it on live equipment.  I am sending up what I believe is the fix now.

**Comment by cbschuld** [comment]
@zolapop - if you are able to update your branch to `setSourceIssue` and test it locally that would be awesome; otherwise I'll flag to test it in July.  Thanks, Chris
