### ISSUE TITLE
Channel Slider UX is a bit wonky sometimes

### ISSUE THREAD

**Issue by drj-io** [cbschuld/monoprice-multizone-interface#4]
First I want to say that this is a great project. We are using both the API and the front end service with our two multizone amps.  

I might look into this a bit further, but sometimes the channel sliders go into "selection" mode while trying to alter the settings in safari. It mostly drives my wife crazy, she's asked to just make it so that there's an integer input.  

I'm not too savvy with TS/React but this CSS snippet might be valuable.

https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting

I might take a look at the code myself when I get time, and if I find a fix, I'll pop in a PR.  Thanks again for the great OSS contribution!

**Comment by cbschuld** [comment]
Hey David (@drj-io) - thanks for the kind words... I'll see if I can fix this up for you.  I am re-cutting it with all of the latest versions and am working on updating a few parts of it.  I'll circle back here when it is done.  Thx for the heads up!

**Comment by cbschuld** [comment]
@drj-io  your wife won't be mad at it - I found the problem... I'll push up a new version here shortly!  thx for the feedback!

**Comment by cbschuld** [comment]
@drj-io - all set ; tested on a few phones here and works great; let your wife know it is no longer stupid 😉
